### ISSUE TITLE
Backup Function File Inclusivity

### ISSUE THREAD

**Issue by ProfessorPinball** [elesiuta/jupyter-nbgrader-helper#1]
I have noticed that the backup utility, when it's backing up the assignment source folder, seems to only be backing up the notebook files (i.e., any auxiliary files, such as *.csv files, are lost).

Seems like a simple tweak, if I'm correct in my assessment.

**Comment by elesiuta** [comment]
You mean for nbhelper --backup source ? I just tested it and it worked for me, it just uses shutil.make_archive to make an archive of the entire folder. Is it possible those files are symlinks? I don't believe it follows those.
